In [8]:
import numpy as np

# EXAMPLE (1) - Create INT

In [9]:
x = np.array([1, 2, 3, 4, 5])

In [10]:
# We print x
print()
print('x = ', x)
print()


x =  [1 2 3 4 5]



In [11]:
# We print information about x
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)

x has dimensions: (5,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int64


# EXAMPLE (2) - Create STR

In [12]:
x = np.array(['Hello', 'World'])

In [13]:
# We print x
print()
print('x = ', x)
print()


x =  ['Hello' 'World']



In [14]:
# We print information about x
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)
x = ['Hello' 'World']

x has dimensions: (2,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: <U5


# EXAMPLE (3) - - Create STR/INT

In [15]:
x = np.array([1, 2, 'World'])

In [16]:
# We print the ndarray
print()
print('x = ', x)
print()


x =  ['1' '2' 'World']



In [17]:
# We print information about x
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)
x = ['1' '2' 'World']

x has dimensions: (3,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: <U21


# EXAMPLE (4) - Create Rank 2 ndarray

In [18]:
# We create a rank 2 ndarray that only contains integers
Y = np.array([[1,2,3],[4,5,6],[7,8,9], [10,11,12]])

In [19]:
# We print Y
print()
print('Y = \n', Y)
print()


Y = 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]



In [20]:
# We print information about Y
print('Y has dimensions:', Y.shape)
print('Y has a total of', Y.size, 'elements')
print('Y is an object of type:', type(Y))
print('The elements in Y are of type:', Y.dtype)

Y has dimensions: (4, 3)
Y has a total of 12 elements
Y is an object of type: <class 'numpy.ndarray'>
The elements in Y are of type: int64


# EXAMPLE (5) - Create Rank 1 ndarray¶

In [21]:
# We create a rank 1 ndarray that contains integers
x = np.array([1,2,3])

In [22]:
# We create a rank 1 ndarray that contains floats
y = np.array([1.0,2.0,3.0])

In [23]:
# We create a rank 1 ndarray that contains integers and floats
z = np.array([1, 2.5, 4])

In [24]:
# We print the dtype of each ndarray
print('The elements in x are of type:', x.dtype)
print('The elements in y are of type:', y.dtype)
print('The elements in z are of type:', z.dtype)

The elements in x are of type: int64
The elements in y are of type: float64
The elements in z are of type: float64


# EXAMPLE (6) - Create float Rank 2 ndarray¶

In [25]:
# We create a rank 1 ndarray of floats but set the dtype to int64
x = np.array([1.5, 2.2, 3.7, 4.0, 5.9], dtype = np.int64)

In [26]:
# We print x
print()
print('x = ', x)
print()


x =  [1 2 3 4 5]



In [27]:
# We print the dtype x
print('The elements in x are of type:', x.dtype)

The elements in x are of type: int64


# EXAMPLE (7) - Save / Load

In [28]:
# We create a rank 1 ndarray
x = np.array([1, 2, 3, 4, 5])

In [29]:
# We save x into the current directory as
np.save('my_array', x)

In [30]:
# We load the saved array from our current directory into variable y
y = np.load('my_array.npy')

In [31]:
# We print y
print()
print('y = ', y)
print()



y =  [1 2 3 4 5]



In [32]:
# We print information about the ndarray we loaded
print('y is an object of type:', type(y))
print('The elements in y are of type:', y.dtype)

y is an object of type: <class 'numpy.ndarray'>
The elements in y are of type: int64


# EXAMPLE (8) - Access element in Rank 1 ndarray

In [33]:
# We create a rank 1 ndarray that contains integers from 1 to 5
x = np.array([1, 2, 3, 4, 5])

In [34]:
# We print x
print()
print('x = ', x)
print()


x =  [1 2 3 4 5]



In [35]:
# Let's access some elements with positive indices
print('This is First Element in x:', x[0])
print('This is Second Element in x:', x[1])
print('This is Fifth (Last) Element in x:', x[4])
print()

This is First Element in x: 1
This is Second Element in x: 2
This is Fifth (Last) Element in x: 5



In [36]:
# Let's access the same elements with negative indices
print('This is First Element in x:', x[-5])
print('This is Second Element in x:', x[-4])
print('This is Fifth (Last) Element in x:', x[-1])

This is First Element in x: 1
This is Second Element in x: 2
This is Fifth (Last) Element in x: 5


# EXAMPLE (9) - Change element in Rank 1 ndarray


In [37]:
# We create a rank 1 ndarray that contains integers from 1 to 5
x = np.array([1, 2, 3, 4, 5])

In [38]:
# We print the original x
print()
print('Original:\n x = ', x)
print()


Original:
 x =  [1 2 3 4 5]



In [39]:
# We change the fourth element in x from 4 to 20
x[3] = 20

In [40]:
# We print x after it was modified
print('Modified:\n x = ', x)

Modified:
 x =  [ 1  2  3 20  5]


# EXAMPLE (10) - Access element in Rank 2 ndarray

In [41]:
# We create a 3 x 3 rank 2 ndarray that contains integers from 1 to 9
X = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [42]:
# We print X
print()
print('X = \n', X)
print()


X = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]



In [43]:
# Let's access some elements in X
print('This is (0,0) Element in X:', X[0,0])
print('This is (0,1) Element in X:', X[0,1])
print('This is (2,2) Element in X:', X[2,2])

This is (0,0) Element in X: 1
This is (0,1) Element in X: 2
This is (2,2) Element in X: 9


# EXAMPLE (11) - Change element in Rank 2 ndarray

In [44]:
# We create a 3 x 3 rank 2 ndarray that contains integers from 1 to 9
X = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [45]:
# We print the original x
print()
print('Original:\n X = \n', X)
print()


Original:
 X = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]



In [46]:
# We change the (0,0) element in X from 1 to 20
X[0,0] = 20

In [47]:
# We print X after it was modified
print('Modified:\n X = \n', X)

Modified:
 X = 
 [[20  2  3]
 [ 4  5  6]
 [ 7  8  9]]


# EXAMPLE (12) - Delete

In [48]:
# We create a rank 1 ndarray
x = np.array([1, 2, 3, 4, 5])

In [49]:
# We create a rank 2 ndarray
Y = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [50]:
# We print x
print()
print('Original x = ', x)


Original x =  [1 2 3 4 5]


In [51]:
# We delete the first and last element of x
x = np.delete(x, [0,4])

In [52]:
# We print x with the first and last element deleted
print()
print('Modified x = ', x)


Modified x =  [2 3 4]


In [53]:
# We print Y
print()
print('Original Y = \n', Y)


Original Y = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [54]:
# We delete the first row of y
w = np.delete(Y, 0, axis=0)

In [55]:
# We delete the first and last column of y
v = np.delete(Y, [0,2], axis=1)

In [56]:
# We print w
print()
print('w = \n', w)


w = 
 [[4 5 6]
 [7 8 9]]


In [57]:
# We print v
print()
print('v = \n', v)


v = 
 [[2]
 [5]
 [8]]


# EXAMPLE (13) - Append

In [58]:
# We create a rank 1 ndarray
x = np.array([1, 2, 3, 4, 5])

In [59]:
# We create a rank 2 ndarray
Y = np.array([[1,2,3],[4,5,6]])

In [60]:
# We print x
print()
print('Original x = ', x)


Original x =  [1 2 3 4 5]


In [61]:
# EXAMPLE (16)
# We append the integer 6 to x
x = np.append(x, 6)

In [62]:
# We print x
print()
print('x = ', x)


x =  [1 2 3 4 5 6]


# EXAMPLE (14) - More Append

In [63]:
# We append the integer 7 and 8 to x
x = np.append(x, [7,8])

In [64]:
# We print x
print()
print('x = ', x)


x =  [1 2 3 4 5 6 7 8]


In [65]:
# We print Y
print()
print('Original Y = \n', Y)


Original Y = 
 [[1 2 3]
 [4 5 6]]


In [66]:
# We append a new row containing 7,8,9 to y
v = np.append(Y, [[7,8,9]], axis=0)

In [67]:
# We append a new column containing 9 and 10 to y
q = np.append(Y,[[9],[10]], axis=1)

In [68]:
# We print v
print()
print('v = \n', v)


v = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [69]:
# We print q
print()
print('q = \n', q)


q = 
 [[ 1  2  3  9]
 [ 4  5  6 10]]


# EXAMPLE (15) - Insert

In [70]:
# We create a rank 1 ndarray
x = np.array([1, 2, 5, 6, 7])

In [71]:
# We create a rank 2 ndarray
Y = np.array([[1,2,3],[7,8,9]])

In [72]:
# We print x
print()
print('Original x = ', x)


Original x =  [1 2 5 6 7]


In [73]:
# We insert the integer 3 and 4 between 2 and 5 in x.
x = np.insert(x,2,[3,4])

In [74]:
# We print x with the inserted elements
print()
print('x = ', x)


x =  [1 2 3 4 5 6 7]


In [75]:
# We print Y
print()
print('Original Y = \n', Y)


Original Y = 
 [[1 2 3]
 [7 8 9]]


In [76]:
# We insert a row between the first and last row of y
w = np.insert(Y,1,[4,5,6],axis=0)

In [77]:
# We insert a column full of 5s between the first and second column of y
v = np.insert(Y,1,5, axis=1)

In [78]:
# We print w
print()
print('w = \n', w)


w = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [79]:
# We print v
print()
print('v = \n', v)


v = 
 [[1 5 2 3]
 [7 5 8 9]]


In [80]:
# We print y
print()
print('y = \n', y)


y = 
 [1 2 3 4 5]


# EXAMPLE (16) - vStack & hStack

In [81]:
# We create a rank 1 ndarray
x = np.array([1,2])

In [82]:
# We create a rank 2 ndarray
Y = np.array([[3,4],[5,6]])

In [83]:
# We print x
print()
print('x = ', x)


x =  [1 2]


In [84]:
# We print Y
print()
print('Y = \n', Y)


Y = 
 [[3 4]
 [5 6]]


In [85]:
# We stack x on top of Y
z = np.vstack((x,Y))

In [86]:
# We stack x on the right of Y. We need to reshape x in order to stack it on the right of Y.
w = np.hstack((Y,x.reshape(2,1)))

In [87]:
# We print z
print()
print('z = \n', z)


z = 
 [[1 2]
 [3 4]
 [5 6]]


In [88]:
# We print w
print()
print('w = \n', w)


w = 
 [[3 4 1]
 [5 6 2]]


# EXAMPLE (17) - Select elements

In [89]:
# We create a 4 x 5 ndarray that contains integers from 0 to 19
X = np.arange(20).reshape(4, 5)

In [90]:
# We print X
print()
print('X = \n', X)
print()


X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]



In [91]:
# We select all the elements that are in the 2nd through 4th rows and in the 3rd to 5th columns
Z = X[1:4,2:5]

In [92]:
# We print Z
print('Z = \n', Z)

Z = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [ ]:
# We can select the same elements as above using method 2
W = X[1:,2:5]

In [68]:
# We print W
print()
print('W = \n', W)


W = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [69]:
# We select all the elements that are in the 1st through 3rd rows and in the 3rd to 4th columns
Y = X[:3,2:5]

In [70]:
# We print Y
print()
print('Y = \n', Y)


Y = 
 [[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]


In [71]:
# We select all the elements in the 3rd row
v = X[2,:]

In [72]:
# We print v
print()
print('v = ', v)


v =  [10 11 12 13 14]


In [73]:
# We select all the elements in the 3rd column
q = X[:,2]

In [74]:
# We print q
print()
print('q = ', q)


q =  [ 2  7 12 17]


In [75]:
# We select all the elements in the 3rd column but return a rank 2 ndarray
R = X[:,2:3]

In [76]:
# We print R
print()
print('R = \n', R)


R = 
 [[ 2]
 [ 7]
 [12]
 [17]]


# EXAMPLE (18) - More select

In [77]:
# We create a 4 x 5 ndarray that contains integers from 0 to 19
X = np.arange(20).reshape(4, 5)

In [78]:
# We print X
print()
print('X = \n', X)
print()


X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]



In [79]:
# We select all the elements that are in the 2nd through 4th rows and in the 3rd to 4th columns
Z = X[1:4,2:5]

In [80]:
# We print Z
print()
print('Z = \n', Z)
print()


Z = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]



In [81]:
# We change the last element in Z to 555
Z[2,2] = 555

In [82]:
# We print X
print()
print('X = \n', X)
print()


X = 
 [[  0   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18 555]]



# EXAMPLE (19) - Copy

In [83]:
# We create a 4 x 5 ndarray that contains integers from 0 to 19
X = np.arange(20).reshape(4, 5)

In [84]:
# We print X
print()
print('X = \n', X)
print()


X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]



In [85]:
# create a copy of the slice using the np.copy() function
Z = np.copy(X[1:4,2:5])

In [86]:
#  create a copy of the slice using the copy as a method
W = X[1:4,2:5].copy()

In [87]:
# We change the last element in Z to 555
Z[2,2] = 555

In [88]:
# We change the last element in W to 444
W[2,2] = 444

In [89]:
# We print X
print()
print('X = \n', X)


X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [90]:
# We print Z
print()
print('Z = \n', Z)


Z = 
 [[  7   8   9]
 [ 12  13  14]
 [ 17  18 555]]


In [91]:
# We print W
print()
print('W = \n', W)


W = 
 [[  7   8   9]
 [ 12  13  14]
 [ 17  18 444]]


# EXAMPLE (20) - Indices to select

In [92]:
# We create a 4 x 5 ndarray that contains integers from 0 to 19
X = np.arange(20).reshape(4, 5)

In [93]:
# We create a rank 1 ndarray that will serve as indices to select elements from X
indices = np.array([1,3])

In [95]:
# We print X
print()
print('X = \n', X)
print()


X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]



In [96]:
# We print indices
print('indices = ', indices)
print()

indices =  [1 3]



In [97]:
# We use the indices ndarray to select the 2nd and 4th row of X
Y = X[indices,:]

In [98]:
# We use the indices ndarray to select the 2nd and 4th column of X
Z = X[:, indices]

In [99]:
# We print Y
print()
print('Y = \n', Y)


Y = 
 [[ 5  6  7  8  9]
 [15 16 17 18 19]]


In [100]:
# We print Z
print()
print('Z = \n', Z)


Z = 
 [[ 1  3]
 [ 6  8]
 [11 13]
 [16 18]]


# EXAMPLE (21) - Diagonal select

In [102]:
# We create a 4 x 5 ndarray that contains integers from 0 to 19
X = np.arange(25).reshape(5, 5)

In [103]:
# We print X
print()
print('X = \n', X)
print()


X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]



In [104]:
# We print the elements in the main diagonal of X
print('z =', np.diag(X))
print()

z = [ 0  6 12 18 24]



In [105]:
# We print the elements above the main diagonal of X
print('y =', np.diag(X, k=1))
print()

y = [ 1  7 13 19]



In [106]:
# We print the elements below the main diagonal of X
print('w = ', np.diag(X, k=-1))

w =  [ 5 11 17 23]


# EXAMPLE (22) - Unique

In [107]:
# Create 3 x 3 ndarray with repeated values
X = np.array([[1,2,3],[5,2,8],[1,2,3]])

In [108]:
# We print X
print()
print('X = \n', X)
print()


X = 
 [[1 2 3]
 [5 2 8]
 [1 2 3]]



In [109]:
# We print the unique elements of X
print('The unique elements in X are:',np.unique(X))

The unique elements in X are: [1 2 3 5 8]


# EXAMPLE (23 - Boolean indexing

In [110]:
# We create a 5 x 5 ndarray that contains integers from 0 to 24
X = np.arange(25).reshape(5, 5)

In [111]:
# We print X
print()
print('Original X = \n', X)
print()


Original X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]



In [113]:
#We use Boolean indexing to select elements in X:
print('The elements in X that are greater than 10:', X[X > 10])
print('The elements in X that less than or equal to 7:', X[X <= 7])
print('The elements in X that are between 10 and 17:', X[(X > 10) & (X < 17)])

The elements in X that are greater than 10: [11 12 13 14 15 16 17 18 19 20 21 22 23 24]
The elements in X that less than or equal to 7: [0 1 2 3 4 5 6 7]
The elements in X that are between 10 and 17: [11 12 13 14 15 16]


In [114]:
# We use Boolean indexing to assign the elements that are between 10 and 17 the value of -1
X[(X > 10) & (X < 17)] = -1

In [115]:
# We print X
print()
print('X = \n', X)
print()


X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 -1 -1 -1 -1]
 [-1 -1 17 18 19]
 [20 21 22 23 24]]



# EXAMPLE (24) - Set operations

In [116]:
# We create a rank 1 ndarray
x = np.array([1,2,3,4,5])

In [117]:
# We create a rank 1 ndarray
y = np.array([6,7,2,8,4])

In [118]:
# We print x
print()
print('x = ', x)


x =  [1 2 3 4 5]


In [119]:
# We print y
print()
print('y = ', y)


y =  [6 7 2 8 4]


In [120]:
# We use set operations to compare x and y:
print()
print('The elements that are both in x and y:', np.intersect1d(x,y))
print('The elements that are in x that are not in y:', np.setdiff1d(x,y))
print('All the elements of x and y:',np.union1d(x,y))


The elements that are both in x and y: [2 4]
The elements that are in x that are not in y: [1 3 5]
All the elements of x and y: [1 2 3 4 5 6 7 8]


# EXAMPLE (25) - Sort rank 1 ndarray

In [122]:
# We create an unsorted rank 1 ndarray
x = np.random.randint(1,11,size=(10,))

In [123]:
# We print x
print()
print('Original x = ', x)


Original x =  [ 1  7  3 10  2  3  2  1  8  4]


In [124]:
# We sort x and print the sorted array using sort as a function.
print()
print('Sorted x (out of place):', np.sort(x))


Sorted x (out of place): [ 1  1  2  2  3  3  4  7  8 10]


In [125]:
# When we sort out of place the original array remains intact. To see this we print x again
print()
print('x after sorting:', x)


x after sorting: [ 1  7  3 10  2  3  2  1  8  4]


In [126]:
# We sort x but only keep the unique elements in x
print(np.sort(np.unique(x)))

[ 1  2  3  4  7  8 10]


# EXAMPLE (26) - More sorting

In [128]:
# We create an unsorted rank 1 ndarray
x = np.random.randint(1,11,size=(10,))

In [129]:
# We print x
print()
print('Original x = ', x)


Original x =  [10  3  7  4  4  9 10  4  9  4]


In [130]:
# We sort x and print the sorted array using sort as a method.
x.sort()

In [131]:
# When we sort in place the original array is changed to the sorted array. To see this we print x again
print()
print('x after sorting:', x)


x after sorting: [ 3  4  4  4  4  7  9  9 10 10]


# EXAMPLE (27) Sort rank 2 ndarray

In [138]:
# We create an unsorted rank 2 ndarray
X = np.random.randint(1,11,size=(5,5))

In [139]:
# We print X
print()
print('Original X = \n', X)
print()


Original X = 
 [[10  3  2 10  8]
 [ 2  4  2  2  9]
 [ 8  6  4  1  8]
 [ 1  1  2  8  7]
 [ 2 10  4  2  3]]



In [140]:
# We sort the columns of X and print the sorted array
print()
print('X with sorted columns :\n', np.sort(X, axis = 0))


X with sorted columns :
 [[ 1  1  2  1  3]
 [ 2  3  2  2  7]
 [ 2  4  2  2  8]
 [ 8  6  4  8  8]
 [10 10  4 10  9]]


In [141]:
# We sort the rows of X and print the sorted array
print()
print('X with sorted rows :\n', np.sort(X, axis = 1))


X with sorted rows :
 [[ 2  3  8 10 10]
 [ 2  2  2  4  9]
 [ 1  4  6  8  8]
 [ 1  1  2  7  8]
 [ 2  2  3  4 10]]


# EXAMPLE (28) - Basic element-wise operations (Rank 1 ndarrays)

In [137]:
# We create two rank 1 ndarrays
x = np.array([1,2,3,4])
y = np.array([5.5,6.5,7.5,8.5])

In [142]:
# We print x
print()
print('x = ', x)


x =  [1 2 3 4]


In [143]:
# We print y
print()
print('y = ', y)
print()


y =  [5.5 6.5 7.5 8.5]



In [144]:
# We perfrom basic element-wise operations using arithmetic symbols and functions
print('x + y = ', x + y)
print('add(x,y) = ', np.add(x,y))
print()
print('x - y = ', x - y)
print('subtract(x,y) = ', np.subtract(x,y))
print()
print('x * y = ', x * y)
print('multiply(x,y) = ', np.multiply(x,y))
print()
print('x / y = ', x / y)
print('divide(x,y) = ', np.divide(x,y))

x + y =  [ 6.5  8.5 10.5 12.5]
add(x,y) =  [ 6.5  8.5 10.5 12.5]

x - y =  [-4.5 -4.5 -4.5 -4.5]
subtract(x,y) =  [-4.5 -4.5 -4.5 -4.5]

x * y =  [ 5.5 13.  22.5 34. ]
multiply(x,y) =  [ 5.5 13.  22.5 34. ]

x / y =  [0.18181818 0.30769231 0.4        0.47058824]
divide(x,y) =  [0.18181818 0.30769231 0.4        0.47058824]


# EXAMPLE (29) - Basic element-wise operations (Rank 2 ndarrays)

In [149]:
# We create two rank 2 ndarrays
X = np.array([1,2,3,4]).reshape(2,2)
Y = np.array([5.5,6.5,7.5,8.5]).reshape(2,2)

In [150]:
# We print X
print()
print('X = \n', X)


X = 
 [[1 2]
 [3 4]]


In [151]:
# We print Y
print()
print('Y = \n', Y)
print()


Y = 
 [[5.5 6.5]
 [7.5 8.5]]



In [152]:
# We perform basic element-wise operations using arithmetic symbols and functions
print('X + Y = \n', X + Y)
print()
print('add(X,Y) = \n', np.add(X,Y))
print()
print('X - Y = \n', X - Y)
print()
print('subtract(X,Y) = \n', np.subtract(X,Y))
print()
print('X * Y = \n', X * Y)
print()
print('multiply(X,Y) = \n', np.multiply(X,Y))
print()
print('X / Y = \n', X / Y)
print()
print('divide(X,Y) = \n', np.divide(X,Y))

X + Y = 
 [[ 6.5  8.5]
 [10.5 12.5]]

add(X,Y) = 
 [[ 6.5  8.5]
 [10.5 12.5]]

X - Y = 
 [[-4.5 -4.5]
 [-4.5 -4.5]]

subtract(X,Y) = 
 [[-4.5 -4.5]
 [-4.5 -4.5]]

X * Y = 
 [[ 5.5 13. ]
 [22.5 34. ]]

multiply(X,Y) = 
 [[ 5.5 13. ]
 [22.5 34. ]]

X / Y = 
 [[0.18181818 0.30769231]
 [0.4        0.47058824]]

divide(X,Y) = 
 [[0.18181818 0.30769231]
 [0.4        0.47058824]]


# EXAMPLE (30) - EXP | SQRT | POWER  (Rank 1 ndarrays)

In [154]:
# We create a rank 1 ndarray
x = np.array([1,2,3,4])

In [155]:
# We print x
print()
print('x = ', x)


x =  [1 2 3 4]


In [156]:
# We apply different mathematical functions to all elements of x
print()
print('EXP(x) =', np.exp(x))
print()
print('SQRT(x) =',np.sqrt(x))
print()
print('POW(x,2) =',np.power(x,2)) # We raise all elements to the power of 2


EXP(x) = [ 2.71828183  7.3890561  20.08553692 54.59815003]

SQRT(x) = [1.         1.41421356 1.73205081 2.        ]

POW(x,2) = [ 1  4  9 16]


# EXAMPLE (31) - Math [1|3]

In [157]:
# We create a 2 x 2 ndarray
X = np.array([[1,2], [3,4]])

In [158]:
# We print x
print()
print('X = \n', X)
print()


X = 
 [[1 2]
 [3 4]]



In [159]:
print('Average of all elements in X:', X.mean())
print('Average of all elements in the columns of X:', X.mean(axis=0))
print('Average of all elements in the rows of X:', X.mean(axis=1))
print()
print('Sum of all elements in X:', X.sum())
print('Sum of all elements in the columns of X:', X.sum(axis=0))
print('Sum of all elements in the rows of X:', X.sum(axis=1))
print()
print('Standard Deviation of all elements in X:', X.std())
print('Standard Deviation of all elements in the columns of X:', X.std(axis=0))
print('Standard Deviation of all elements in the rows of X:', X.std(axis=1))
print()
print('Median of all elements in X:', np.median(X))
print('Median of all elements in the columns of X:', np.median(X,axis=0))
print('Median of all elements in the rows of X:', np.median(X,axis=1))
print()
print('Maximum value of all elements in X:', X.max())
print('Maximum value of all elements in the columns of X:', X.max(axis=0))
print('Maximum value of all elements in the rows of X:', X.max(axis=1))
print()
print('Minimum value of all elements in X:', X.min())
print('Minimum value of all elements in the columns of X:', X.min(axis=0))
print('Minimum value of all elements in the rows of X:', X.min(axis=1))

Average of all elements in X: 2.5
Average of all elements in the columns of X: [2. 3.]
Average of all elements in the rows of X: [1.5 3.5]

Sum of all elements in X: 10
Sum of all elements in the columns of X: [4 6]
Sum of all elements in the rows of X: [3 7]

Standard Deviation of all elements in X: 1.118033988749895
Standard Deviation of all elements in the columns of X: [1. 1.]
Standard Deviation of all elements in the rows of X: [0.5 0.5]

Median of all elements in X: 2.5
Median of all elements in the columns of X: [2. 3.]
Median of all elements in the rows of X: [1.5 3.5]

Maximum value of all elements in X: 4
Maximum value of all elements in the columns of X: [3 4]
Maximum value of all elements in the rows of X: [2 4]

Minimum value of all elements in X: 1
Minimum value of all elements in the columns of X: [1 2]
Minimum value of all elements in the rows of X: [1 3]


# EXAMPLE (32) - Math [2|3]

In [161]:
# We create a 2 x 2 ndarray
X = np.array([[1,2], [3,4]])

In [162]:
# We print x
print()
print('X = \n', X)
print()

print('3 * X = \n', 3 * X)
print()
print('3 + X = \n', 3 + X)
print()
print('X - 3 = \n', X - 3)
print()
print('X / 3 = \n', X / 3)


X = 
 [[1 2]
 [3 4]]

3 * X = 
 [[ 3  6]
 [ 9 12]]

3 + X = 
 [[4 5]
 [6 7]]

X - 3 = 
 [[-2 -1]
 [ 0  1]]

X / 3 = 
 [[0.33333333 0.66666667]
 [1.         1.33333333]]


# EXAMPLE (33) - Math [3|3]

In [163]:
# We create a rank 1 ndarray
x = np.array([1,2,3])

In [164]:
# We create a 3 x 3 ndarray
Y = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [165]:
# We create a 3 x 1 ndarray
Z = np.array([1,2,3]).reshape(3,1)

In [166]:
# We print x
print()
print('x = ', x)
print()


x =  [1 2 3]



In [167]:
# We print Y
print()
print('Y = \n', Y)
print()


Y = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]



In [168]:
# We print Z
print()
print('Z = \n', Z)
print()


Z = 
 [[1]
 [2]
 [3]]



In [169]:
print('x + Y = \n', x + Y)
print()
print('Z + Y = \n',Z + Y)

x + Y = 
 [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]

Z + Y = 
 [[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]
