In [1]:
import numpy as np

In [2]:
# We create a 1D ndarray that contains only integers
x = np.array([1, 2, 3, 4, 5])

In [3]:
# Let's print the ndarray we just created using the print() command
print('x = ', x)

x =  [1 2 3 4 5]


In [4]:
# EXAMPLE (1.1)
x = np.array([1, 2, 3, 4, 5])

In [5]:
# We print x
print()
print('x = ', x)
print()


x =  [1 2 3 4 5]



In [6]:
# We print information about x
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)

x has dimensions: (5,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int64


In [7]:
# EXAMPLE (2)
x = np.array(['Hello', 'World'])

In [8]:
# We print x
print()
print('x = ', x)
print()


x =  ['Hello' 'World']



In [9]:
# We print information about x
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)
x = ['Hello' 'World']

x has dimensions: (2,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: <U5


In [12]:
# EXAMPLE (3)
x = np.array([1, 2, 'World'])

In [11]:
# We print the ndarray
print()
print('x = ', x)
print()


x =  ['1' '2' 'World']



In [13]:
# We print information about x
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)
x = ['1' '2' 'World']

x has dimensions: (3,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: <U21


In [14]:
# EXAMPLE (4)
# We create a rank 2 ndarray that only contains integers
Y = np.array([[1,2,3],[4,5,6],[7,8,9], [10,11,12]])

In [15]:
# We print Y
print()
print('Y = \n', Y)
print()


Y = 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]



In [16]:
# We print information about Y
print('Y has dimensions:', Y.shape)
print('Y has a total of', Y.size, 'elements')
print('Y is an object of type:', type(Y))
print('The elements in Y are of type:', Y.dtype)

Y has dimensions: (4, 3)
Y has a total of 12 elements
Y is an object of type: <class 'numpy.ndarray'>
The elements in Y are of type: int64


In [17]:
# EXAMPLE (5)
# We create a rank 1 ndarray that contains integers
x = np.array([1,2,3])

In [18]:
# We create a rank 1 ndarray that contains floats
y = np.array([1.0,2.0,3.0])

In [19]:
# We create a rank 1 ndarray that contains integers and floats
z = np.array([1, 2.5, 4])

In [20]:
# We print the dtype of each ndarray
print('The elements in x are of type:', x.dtype)
print('The elements in y are of type:', y.dtype)
print('The elements in z are of type:', z.dtype)

The elements in x are of type: int64
The elements in y are of type: float64
The elements in z are of type: float64


In [21]:
# EXAMPLE (6)
# We create a rank 1 ndarray of floats but set the dtype to int64
x = np.array([1.5, 2.2, 3.7, 4.0, 5.9], dtype = np.int64)

In [22]:
# We print x
print()
print('x = ', x)
print()


x =  [1 2 3 4 5]



In [23]:
# We print the dtype x
print('The elements in x are of type:', x.dtype)

The elements in x are of type: int64


In [24]:
# EXAMPLE (8)
# We create a rank 1 ndarray
x = np.array([1, 2, 3, 4, 5])

In [25]:
# We save x into the current directory as
np.save('my_array', x)

In [26]:
# We load the saved array from our current directory into variable y
y = np.load('my_array.npy')

In [27]:
# We print y
print()
print('y = ', y)
print()



y =  [1 2 3 4 5]



In [28]:
# We print information about the ndarray we loaded
print('y is an object of type:', type(y))
print('The elements in y are of type:', y.dtype)

y is an object of type: <class 'numpy.ndarray'>
The elements in y are of type: int64


In [29]:
# EXAMPLE (9)
# We create a rank 1 ndarray that contains integers from 1 to 5
x = np.array([1, 2, 3, 4, 5])

In [30]:
# We print x
print()
print('x = ', x)
print()


x =  [1 2 3 4 5]



In [31]:
# Let's access some elements with positive indices
print('This is First Element in x:', x[0])
print('This is Second Element in x:', x[1])
print('This is Fifth (Last) Element in x:', x[4])
print()

This is First Element in x: 1
This is Second Element in x: 2
This is Fifth (Last) Element in x: 5



In [32]:
# Let's access the same elements with negative indices
print('This is First Element in x:', x[-5])
print('This is Second Element in x:', x[-4])
print('This is Fifth (Last) Element in x:', x[-1])

This is First Element in x: 1
This is Second Element in x: 2
This is Fifth (Last) Element in x: 5


In [33]:
# EXAMPLE (10)
# We create a rank 1 ndarray that contains integers from 1 to 5
x = np.array([1, 2, 3, 4, 5])

In [34]:
# We print the original x
print()
print('Original:\n x = ', x)
print()


Original:
 x =  [1 2 3 4 5]



In [35]:
# We change the fourth element in x from 4 to 20
x[3] = 20

In [36]:
# We print x after it was modified
print('Modified:\n x = ', x)

Modified:
 x =  [ 1  2  3 20  5]


In [37]:
# EXAMPLE (11)
# We create a 3 x 3 rank 2 ndarray that contains integers from 1 to 9
X = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [38]:
# We print X
print()
print('X = \n', X)
print()


X = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]



In [39]:
# Let's access some elements in X
print('This is (0,0) Element in X:', X[0,0])
print('This is (0,1) Element in X:', X[0,1])
print('This is (2,2) Element in X:', X[2,2])

This is (0,0) Element in X: 1
This is (0,1) Element in X: 2
This is (2,2) Element in X: 9


In [40]:
# EXAMPLE (12)
# We create a 3 x 3 rank 2 ndarray that contains integers from 1 to 9
X = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [41]:
# We print the original x
print()
print('Original:\n X = \n', X)
print()


Original:
 X = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]



In [42]:
# We change the (0,0) element in X from 1 to 20
X[0,0] = 20

In [43]:
# We print X after it was modified
print('Modified:\n X = \n', X)

Modified:
 X = 
 [[20  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [44]:
# EXAMPLE (13)
# We create a rank 1 ndarray
x = np.array([1, 2, 3, 4, 5])

In [45]:
# We create a rank 2 ndarray
Y = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [46]:
# We print x
print()
print('Original x = ', x)


Original x =  [1 2 3 4 5]


In [47]:
# EXAMPLE (14)
# We delete the first and last element of x
x = np.delete(x, [0,4])

In [48]:
# We print x with the first and last element deleted
print()
print('Modified x = ', x)


Modified x =  [2 3 4]


In [49]:
# We print Y
print()
print('Original Y = \n', Y)


Original Y = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [50]:
# We delete the first row of y
w = np.delete(Y, 0, axis=0)

In [51]:
# We delete the first and last column of y
v = np.delete(Y, [0,2], axis=1)

In [52]:
# We print w
print()
print('w = \n', w)


w = 
 [[4 5 6]
 [7 8 9]]


In [53]:
# We print v
print()
print('v = \n', v)


v = 
 [[2]
 [5]
 [8]]


In [54]:
# EXAMPLE (15)
# We create a rank 1 ndarray
x = np.array([1, 2, 3, 4, 5])

In [55]:
# We create a rank 2 ndarray
Y = np.array([[1,2,3],[4,5,6]])

In [56]:
# We print x
print()
print('Original x = ', x)


Original x =  [1 2 3 4 5]


In [57]:
# EXAMPLE (16)
# We append the integer 6 to x
x = np.append(x, 6)

In [58]:
# We print x
print()
print('x = ', x)


x =  [1 2 3 4 5 6]


In [59]:
# EXAMPLE (17)
# We append the integer 7 and 8 to x
x = np.append(x, [7,8])

In [60]:
# We print x
print()
print('x = ', x)


x =  [1 2 3 4 5 6 7 8]


In [61]:
# We print Y
print()
print('Original Y = \n', Y)


Original Y = 
 [[1 2 3]
 [4 5 6]]


In [62]:
# We append a new row containing 7,8,9 to y
v = np.append(Y, [[7,8,9]], axis=0)

In [63]:
# We append a new column containing 9 and 10 to y
q = np.append(Y,[[9],[10]], axis=1)

In [64]:
# We print v
print()
print('v = \n', v)


v = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [65]:
# We print q
print()
print('q = \n', q)


q = 
 [[ 1  2  3  9]
 [ 4  5  6 10]]
